# Generated by Django 5.0 on 2023-12-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='first_registration',
            new_name='ITP_valabil_pana_la',
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='actual_odometer',
            new_name='kilometraj_actual',
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='license_plate',
            new_name='numar_inmatriculare',
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='technical_inspection_valid_to',
            new_name='prima_inmatriculare',
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='vin_nr',
            new_name='serie_sasiu',
        ),
    ]
