# Generated by Django 5.0 on 2023-12-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0002_rename_first_registration_camion_itp_valabil_pana_la_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='updated_at',
            new_name='actualizat_la',
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='created_at',
            new_name='creeat_la',
        ),
    ]
