# Generated by Django 5.0 on 2023-12-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0003_rename_updated_at_camion_actualizat_la_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='asigurare_valabila_pana_la',
            field=models.DateField(auto_now=True),
        ),
    ]
