# Generated by Django 5.0 on 2023-12-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0004_camion_asigurare_valabila_pana_la'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='asigurare_valabila_pana_la',
            field=models.DateField(),
        ),
    ]
