# Generated by Django 5.0 on 2023-12-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sofer',
            old_name='start_date',
            new_name='data_incepere',
        ),
        migrations.RenameField(
            model_name='sofer',
            old_name='age',
            new_name='numar_de_telefon',
        ),
        migrations.RenameField(
            model_name='sofer',
            old_name='first_name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='sofer',
            old_name='last_name',
            new_name='prenume',
        ),
        migrations.RenameField(
            model_name='sofer',
            old_name='phone_number',
            new_name='varsta',
        ),
        migrations.AlterField(
            model_name='sofer',
            name='gender',
            field=models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=8),
        ),
    ]
